name: CI
on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: dtolnay/rust-toolchain@stable
      - name: Install HAProxy
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends software-properties-common
          sudo add-apt-repository ppa:vbernat/haproxy-3.2 -y
          sudo apt-get install haproxy=3.2.\*
        shell: bash
      - name: Run tests
        run: |
          cargo test -p haproxy-otel-tests
        shell: bash

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy
      - uses: giraffate/clippy-action@a6030db3b8bde89e5316ff1adb2a0d8954c2ff40 # v1.0.0
        with:
          reporter: 'github-pr-review'
